Added support for directories #1
Tresquel/JSONCleaner pull request #2
Opened 2021-04-29 01:13 UTC by nclsbayona

I would suggest changing the sys.argv approach to argparser or argh or something like those

2021-04-29 11:02 UTC, Tresquel requested changes
First up thank you so much for contributing but there's a few things we could change.

2021-04-29 11:02 UTC, Tresquel commented on JSONCleaner.py
>  def FormatJSONFile(PathToJSONFile):
We could merge this function into the `formatJson` one

2021-04-29 11:02 UTC, Tresquel commented on JSONCleaner.py
>  def DeFormatJSONFile(PathToJSONFile):
We could merge this function into 'deformatJson` too

2021-04-29 11:07 UTC, Tresquel commented
And as you said we could try something like `argparse` or `argh`.

2021-04-29 20:14 UTC, nclsbayona commented
I'm sorry, I didn't mean it was ready, I misclicked

2021-05-01 14:45 UTC, Tresquel commented
You created a second pull request which was merged so I'm gonna close this one

2021-05-01 14:45 UTC, closed without merging