Changed to argparser
Tresquel/JSONCleaner pull request #4
Opened 2021-05-01 18:56 UTC by nclsbayona

2021-05-02 12:30 UTC, Tresquel requested changes
I don't know why is there a conflict but I'm gonna try to fix it once you'll delete `sys` since we don't need it.

2021-05-02 12:30 UTC, Tresquel commented on JSONCleaner.py
>  import sys
We won't need `sys` since we're using `argparse`.

2021-05-04 21:06 UTC, nclsbayona commented
Done

2021-05-04 21:12 UTC, Tresquel approved these changes

2021-05-04 21:12 UTC, merged